name: Hello World WINDOWS

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: windows-latest

    steps:
      - name: Print Hello World
        run: echo "Hello World no windows"
